### ISSUE TITLE
评论区按热度/时间排序切换功能异常

### ISSUE THREAD

**Issue by Frankicy** [MotooriKashin/Bilibili-2019#16]
## 问题描述：
网页切换评论排序关键字时无响应，作为对比，关闭油猴脚本后排序切换功能恢复正常

## 环境：
window11 firefox 油猴插件 启用恢复旧版评论区功能

## 脚本开启时：
<img width="627" alt="脚本开启状态 按热度排序" src="https://github.com/user-attachments/assets/c2d32a03-4509-42f1-8b19-a5351f2ae431">

<img width="533" alt="脚本开启状态 按时间排序" src="https://github.com/user-attachments/assets/57a98242-a694-4c90-a0e3-aa30313b0c50">

## 脚本关闭时：
<img width="430" alt="脚本关闭状态 按热度排序" src="https://github.com/user-attachments/assets/6ecfabd9-f520-4411-8b8a-935b7befc7dd">

<img width="332" alt="脚本关闭状态 按时间排序" src="https://github.com/user-attachments/assets/1557ce75-a871-4f7f-8904-0251f0a211ba">

**Comment by MotooriKashin** [comment]
翻页评论接口失效了，只能说是迟早的事，要修的话只能适应瀑布流评论区了。

**Comment by MotooriKashin** [comment]
已回归瀑布流评论区，那个仓库取消归档了，有问题回那边去吧
